RTS2_FITS_LUTs = {}

RTS2_FITS_LUTs['BNL'] = {
    0 : {
#        'MJD'       : 'JD',
#        'MONDIODE'  : 'AMP0.CURRENT.MIN',
        'MONOWL'    : 'MONOCH.WAVELENG',
        'FILTER'    : 'MONOCH.FILT_1',
        'CONTROLL'  : 'INSTRUME',
        'CCDTEMP'   : 'CRYO.C.TEMP',
        'IMGTYPE'   : 'TESTTYPE',
        'TEMP_SET'  : 'CRYO.2.SETPT',
        'CTLRCFG'   : 'CONFIG',
        'TSTAND'    : 'TELESCOP',
        'CCD_SERN'  : 'CCD_SER'
        },
    'TEST_COND' : {
        'MONOWL'    : 'MONOCH.WAVELENG',
        'FILTER'    : 'MONOCH.FILT_1',
        'CCDTEMP'   : 'CRYO.C.TEMP',
        'TEMP_SET'  : 'CRYO.2.SETPT'
        },
    'CCD_COND' : {
        'V_OD1' : 'BIAS_1.OD1_Vmeas',
        'V_OD2' : 'BIAS_1.OD2_Vmeas',
        'V_OD3' : 'BIAS_1.OD3_Vmeas',
        'V_OD4' : 'BIAS_1.OD4_Vmeas',
        'V_OD5' : 'BIAS_1.OD5_Vmeas',
        'V_OD6' : 'BIAS_1.OD6_Vmeas',
        'V_OD7' : 'BIAS_1.OD7_Vmeas',
        'V_OD8' : 'BIAS_1.OD8_Vmeas',
        'V_OD9' : 'BIAS_1.OD1_Vmeas',
        'V_OD10' : 'BIAS_1.OD2_Vmeas',
        'V_OD11' : 'BIAS_1.OD3_Vmeas',
        'V_OD12' : 'BIAS_1.OD4_Vmeas',
        'V_OD13' : 'BIAS_1.OD5_Vmeas',
        'V_OD14' : 'BIAS_1.OD6_Vmeas',
        'V_OD15' : 'BIAS_1.OD7_Vmeas',
        'V_OD16' : 'BIAS_1.OD8_Vmeas',
        'V_RD1' : 'BIAS_2.RD_Vmeas',
        'V_RD2' : 'BIAS_2.RD_Vmeas',
        'V_RD3' : 'BIAS_2.RD_Vmeas',
        'V_RD4' : 'BIAS_2.RD_Vmeas',
        'V_RD5' : 'BIAS_2.RD_Vmeas',
        'V_RD6' : 'BIAS_2.RD_Vmeas',
        'V_RD7' : 'BIAS_2.RD_Vmeas',
        'V_RD8' : 'BIAS_2.RD_Vmeas',
        'V_RD9' : 'BIAS_2.RD_Vmeas',
        'V_RD10' : 'BIAS_2.RD_Vmeas',
        'V_RD11' : 'BIAS_2.RD_Vmeas',
        'V_RD12' : 'BIAS_2.RD_Vmeas',
        'V_RD13' : 'BIAS_2.RD_Vmeas',
        'V_RD14' : 'BIAS_2.RD_Vmeas',
        'V_RD15' : 'BIAS_2.RD_Vmeas',
        'V_RD16' : 'BIAS_2.RD_Vmeas',
        'V_OG1' : 'BIAS_1.OG_Vmeas',
        'V_OG2' : 'BIAS_1.OG_Vmeas',
        'V_OG3' : 'BIAS_1.OG_Vmeas',
        'V_OG4' : 'BIAS_1.OG_Vmeas',
        'V_OG5' : 'BIAS_1.OG_Vmeas',
        'V_OG6' : 'BIAS_1.OG_Vmeas',
        'V_OG7' : 'BIAS_1.OG_Vmeas',
        'V_OG8' : 'BIAS_1.OG_Vmeas',
        'V_OG9' : 'BIAS_1.OG_Vmeas',
        'V_OG10' : 'BIAS_1.OG_Vmeas',
        'V_OG11' : 'BIAS_1.OG_Vmeas',
        'V_OG12' : 'BIAS_1.OG_Vmeas',
        'V_OG13' : 'BIAS_1.OG_Vmeas',
        'V_OG14' : 'BIAS_1.OG_Vmeas',
        'V_OG15' : 'BIAS_1.OG_Vmeas',
        'V_OG16' : 'BIAS_1.OG_Vmeas',
        'V_S1L' : 'DRV_1.S1_low',
        'V_S1H' : 'DRV_1.S1_high',
        'V_S2L' : 'DRV_1.S2_low',
        'V_S2H' : 'DRV_1.S2_high',
        'V_S3L' : 'DRV_1.S3_low',
        'V_S3H' : 'DRV_1.S3_high',
        'V_RGL' : 'DRV_1.RG_low',
        'V_RGH' : 'DRV_1.RG_high',
        'V_P1L' : 'DRV_1.P1_low',
        'V_P1H' : 'DRV_1.P1_high',
        'V_P2L' : 'DRV_1.P2_low',
        'V_P2H' : 'DRV_1.P2_high',
        'V_P3L' : 'DRV_1.P3_low',
        'V_P3H' : 'DRV_1.P3_high',
        'V_P4L' : 'DRV_1.P4_low',
        'V_P4H' : 'DRV_1.P4_high',
        'I_OD1' : 'BIAS_1.OD1_Cmeas',
        'I_OD2' : 'BIAS_1.OD2_Cmeas',
        'I_OD3' : 'BIAS_1.OD3_Cmeas',
        'I_OD4' : 'BIAS_1.OD4_Cmeas',
        'I_OD5' : 'BIAS_1.OD5_Cmeas',
        'I_OD6' : 'BIAS_1.OD6_Cmeas',
        'I_OD7' : 'BIAS_1.OD7_Cmeas',
        'I_OD8' : 'BIAS_1.OD8_Cmeas',
        'I_OD9' : 'BIAS_1.OD1_Cmeas',
        'I_OD10' : 'BIAS_1.OD2_Cmeas',
        'I_OD11' : 'BIAS_1.OD3_Cmeas',
        'I_OD12' : 'BIAS_1.OD4_Cmeas',
        'I_OD13' : 'BIAS_1.OD5_Cmeas',
        'I_OD14' : 'BIAS_1.OD6_Cmeas',
        'I_OD15' : 'BIAS_1.OD7_Cmeas',
        'I_OD16' : 'BIAS_1.OD8_Cmeas',
        'I_RD1' : 'BIAS_2.RD_Cmeas',
        'I_RD2' : 'BIAS_2.RD_Cmeas',
        'I_RD3' : 'BIAS_2.RD_Cmeas',
        'I_RD4' : 'BIAS_2.RD_Cmeas',
        'I_RD5' : 'BIAS_2.RD_Cmeas',
        'I_RD6' : 'BIAS_2.RD_Cmeas',
        'I_RD7' : 'BIAS_2.RD_Cmeas',
        'I_RD8' : 'BIAS_2.RD_Cmeas',
        'I_RD9' : 'BIAS_2.RD_Cmeas',
        'I_RD10' : 'BIAS_2.RD_Cmeas',
        'I_RD11' : 'BIAS_2.RD_Cmeas',
        'I_RD12' : 'BIAS_2.RD_Cmeas',
        'I_RD13' : 'BIAS_2.RD_Cmeas',
        'I_RD14' : 'BIAS_2.RD_Cmeas',
        'I_RD15' : 'BIAS_2.RD_Cmeas',
        'I_RD16' : 'BIAS_2.RD_Cmeas',
        'I_OG1' : 'BIAS_1.OG_Cmeas',
        'I_OG2' : 'BIAS_1.OG_Cmeas',
        'I_OG3' : 'BIAS_1.OG_Cmeas',
        'I_OG4' : 'BIAS_1.OG_Cmeas',
        'I_OG5' : 'BIAS_1.OG_Cmeas',
        'I_OG6' : 'BIAS_1.OG_Cmeas',
        'I_OG7' : 'BIAS_1.OG_Cmeas',
        'I_OG8' : 'BIAS_1.OG_Cmeas',
        'I_OG9' : 'BIAS_1.OG_Cmeas',
        'I_OG10' : 'BIAS_1.OG_Cmeas',
        'I_OG11' : 'BIAS_1.OG_Cmeas',
        'I_OG12' : 'BIAS_1.OG_Cmeas',
        'I_OG13' : 'BIAS_1.OG_Cmeas',
        'I_OG14' : 'BIAS_1.OG_Cmeas',
        'I_OG15' : 'BIAS_1.OG_Cmeas',
        'I_OG16' : 'BIAS_1.OG_Cmeas'
        }
    }

RTS2_FITS_LUTs['HARVARD'] = {
    0 : {
#        'MJD'       : 'JD',
        'MONDIODE'  : 'K_PHOT.CURRENT',
        'MONOWL'    : 'MONO.WAVELENG',
        'FILTER'    : 'MONO.FILT',
        'CONTROLL'  : 'INSTRUME',
        'CCDTEMP'   : 'LAKESHORE.A.TEMP',
        'IMGTYPE'   : 'TESTTYPE',
        'TEMP_SET'  : 'LAKESHORE.SETPOINT',
        'CTLRCFG'   : 'SIGFILE',  # don't know what you want here
        'TSTAND'    : 'TELESCOP',
        'CCD_SERN'  : 'CCD_SER'
        },
    'TEST_COND' : {
        'MONOWL'    : 'MONO.WAVELENG',
        'FILTER'    : 'MONO.FILTER',
        'CCDTEMP'   : 'LAKESHORE.A.TEMP',
        'TEMP_SET'  : 'LAKESHORE.SETPOINT'
        },
    'CCD_COND' : {
        'V_OD1' : 'OD1_R',
        'V_OD2' : 'OD1_R',
        'V_OD3' : 'OD1_R',
        'V_OD4' : 'OD1_R',
        'V_OD5' : 'OD1_R',
        'V_OD6' : 'OD1_R',
        'V_OD7' : 'OD1_R',
        'V_OD8' : 'OD1_R',
        'V_OD9' : 'OD1_R',
        'V_OD10' : 'OD1_R',
        'V_OD11' : 'OD1_R',
        'V_OD12' : 'OD1_R',
        'V_OD13' : 'OD1_R',
        'V_OD14' : 'OD1_R',
        'V_OD15' : 'OD1_R',
        'V_OD16' : 'OD1_R',
        'V_RD1' : 'RD',
        'V_RD2' : 'RD',
        'V_RD3' : 'RD',
        'V_RD4' : 'RD',
        'V_RD5' : 'RD',
        'V_RD6' : 'RD',
        'V_RD7' : 'RD',
        'V_RD8' : 'RD',
        'V_RD9' : 'RD',
        'V_RD10' : 'RD',
        'V_RD11' : 'RD',
        'V_RD12' : 'RD',
        'V_RD13' : 'RD',
        'V_RD14' : 'RD',
        'V_RD15' : 'RD',
        'V_RD16' : 'RD',
        'V_OG1' : 'OG1_R',
        'V_OG2' : 'OG1_R',
        'V_OG3' : 'OG1_R',
        'V_OG4' : 'OG1_R',
        'V_OG5' : 'OG1_R',
        'V_OG6' : 'OG1_R',
        'V_OG7' : 'OG1_R',
        'V_OG8' : 'OG1_R',
        'V_OG9' : 'OG1_R',
        'V_OG10' : 'OG1_R',
        'V_OG11' : 'OG1_R',
        'V_OG12' : 'OG1_R',
        'V_OG13' : 'OG1_R',
        'V_OG14' : 'OG1_R',
        'V_OG15' : 'OG1_R',
        'V_OG16' : 'OG1_R',
        'V_S1L' : 'SLO',
        'V_S1H' : 'SHI',
        'V_S2L' : 'SLO',
        'V_S2H' : 'SHI',
        'V_S3L' : 'SLO',
        'V_S3H' : 'SHI',
        'V_RGL' : 'RLO',
        'V_RGH' : 'RHI',
        'V_P1L' : 'PLO',
        'V_P1H' : 'PHI',
        'V_P2L' : 'PLO',
        'V_P2H' : 'PHI',
        'V_P3L' : 'PLO',
        'V_P3H' : 'PHI',
        'V_P4L' : 'PLO',
        'V_P4H' : 'PHI',
#        'I_OD1' : 'BIAS_1.OD1_Cmeas',
#        'I_OD2' : 'BIAS_1.OD2_Cmeas',
#        'I_OD3' : 'BIAS_1.OD3_Cmeas',
#        'I_OD4' : 'BIAS_1.OD4_Cmeas',
#        'I_OD5' : 'BIAS_1.OD5_Cmeas',
#        'I_OD6' : 'BIAS_1.OD6_Cmeas',
#        'I_OD7' : 'BIAS_1.OD7_Cmeas',
#        'I_OD8' : 'BIAS_1.OD8_Cmeas',
#        'I_OD9' : 'BIAS_1.OD1_Cmeas',
#        'I_OD10' : 'BIAS_1.OD2_Cmeas',
#        'I_OD11' : 'BIAS_1.OD3_Cmeas',
#        'I_OD12' : 'BIAS_1.OD4_Cmeas',
#        'I_OD13' : 'BIAS_1.OD5_Cmeas',
#        'I_OD14' : 'BIAS_1.OD6_Cmeas',
#        'I_OD15' : 'BIAS_1.OD7_Cmeas',
#        'I_OD16' : 'BIAS_1.OD8_Cmeas',
#        'I_RD1' : 'BIAS_2.RD_Cmeas',
#        'I_RD2' : 'BIAS_2.RD_Cmeas',
#        'I_RD3' : 'BIAS_2.RD_Cmeas',
#        'I_RD4' : 'BIAS_2.RD_Cmeas',
#        'I_RD5' : 'BIAS_2.RD_Cmeas',
#        'I_RD6' : 'BIAS_2.RD_Cmeas',
#        'I_RD7' : 'BIAS_2.RD_Cmeas',
#        'I_RD8' : 'BIAS_2.RD_Cmeas',
#        'I_RD9' : 'BIAS_2.RD_Cmeas',
#        'I_RD10' : 'BIAS_2.RD_Cmeas',
#        'I_RD11' : 'BIAS_2.RD_Cmeas',
#        'I_RD12' : 'BIAS_2.RD_Cmeas',
#        'I_RD13' : 'BIAS_2.RD_Cmeas',
#        'I_RD14' : 'BIAS_2.RD_Cmeas',
#        'I_RD15' : 'BIAS_2.RD_Cmeas',
#        'I_RD16' : 'BIAS_2.RD_Cmeas',
#        'I_OG1' : 'BIAS_1.OG_Cmeas',
#        'I_OG2' : 'BIAS_1.OG_Cmeas',
#        'I_OG3' : 'BIAS_1.OG_Cmeas',
#        'I_OG4' : 'BIAS_1.OG_Cmeas',
#        'I_OG5' : 'BIAS_1.OG_Cmeas',
#        'I_OG6' : 'BIAS_1.OG_Cmeas',
#        'I_OG7' : 'BIAS_1.OG_Cmeas',
#        'I_OG8' : 'BIAS_1.OG_Cmeas',
#        'I_OG9' : 'BIAS_1.OG_Cmeas',
#        'I_OG10' : 'BIAS_1.OG_Cmeas',
#        'I_OG11' : 'BIAS_1.OG_Cmeas',
#        'I_OG12' : 'BIAS_1.OG_Cmeas',
#        'I_OG13' : 'BIAS_1.OG_Cmeas',
#        'I_OG14' : 'BIAS_1.OG_Cmeas',
#        'I_OG15' : 'BIAS_1.OG_Cmeas',
#        'I_OG16' : 'BIAS_1.OG_Cmeas'
        }
    }

sensor_geom = {'ITL' : {'nx' : 509,
                        'ny' : 2000,
                        'prescan' : 3,
                        'vendor' : 'ITL'},
               'E2V' :  {'nx' : 512,
                         'ny' : 2002,
                         'prescan' : 10,
                         'vendor' : 'E2V'}
           }
