#--------- This file is automatically generated by LSST's sconsUtils ---------#
__version__ = '0.0.31-2-g2318d23'
__repo_version__ = '0.0.31-2-g2318d23'
__fingerprint__ = '2318d23ecccd168c0b038266b02b5daf2652cec4'
__dependency_versions__ = {
    'boost': '1.60+1',
    'python': 'unknown',
    'boost_regex': '1.60+1',
    'base': '12.0',
    'pex_exceptions': '12.0',
    'numpy': 'system',
    'utils': '12.0',
    'daf_base': '12.0',
    'boost_system': '1.60+1',
    'boost_filesystem': '1.60+1',
    'pex_logging': '12.0',
    'pex_policy': '12.0',
    'mariadbclient': '10.1.11.lsst3',
    'boost_serialization': '1.60+1',
    'daf_persistence': '12.0',
    'pex_config': '12.0',
    'eigen': '3.2.5.lsst1',
    'fftw': '3.3.4.lsst2',
    'ndarray': '12.0',
    'minuit2': '5.34.14',
    'gsl': '1.16.lsst3',
    'cfitsio': '3360.lsst4',
    'wcslib': '5.13.lsst1',
    'cuda_toolkit': None,
    'afw': '12.0',
    'boost_math': '1.60+1',
    'meas_base': '12.0',
    'pipe_base': '12.0',
    'meas_algorithms': '12.0',
}
__all__ = ('__version__', '__repo_version__', '__fingerprint__', '__dependency_versions__')
